[package]
name = "radb"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
bytes = "1.10"
rsa = { version = "0.9", features = ["pem", "hazmat"] }
pkcs8 = { version = "0.10", features = ["pem", "std"] }
sha1 = "0.10"
base64 = "0.22"
rand = "0.8"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
